### ISSUE TITLE
Trojan ?

### ISSUE THREAD

**Issue by ovcr-Darktooth** [daids/customer#1]
ESET NOD 32 detect this : 
Win32/Packed.VMProtect.ABO
![image](https://user-images.githubusercontent.com/23282377/54468560-2bf64a00-478e-11e9-84a4-97ef2a16c333.png)

**Comment by meng0609** [comment]
Which file name or file link? @Darkouille81

**Comment by ovcr-Darktooth** [comment]
the .exe : 
![image](https://user-images.githubusercontent.com/23282377/54704020-3f146b80-4b3a-11e9-94d6-9a0cb8b1cb07.png)

**Comment by meng0609** [comment]
In the past, the firmware upgrade program for the security measures, we have "Virbox Protector" processing, which caused some anti-virus protection programs, will falsely report this program as a virus, the latest firmware version, has removed the "Virbox Protector", This program is still under test and will be released next week.

**Comment by ovcr-Darktooth** [comment]
i disabled ESET Nod 32 for 10 min, i installed the firmware, i enabled back, everythings seems good.
I've made some research and yea, the file is just protected so it make a false detect, Well i close the issue or u close it ?

**Comment by meng0609** [comment]
You can close it directly, thank you for your support of our products.
